language: generic

matrix:
  include:
    - os: linux
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - cmake
            - cmake-data
            - libboost1.55-all-dev
          sources: &sources
            - boost-latest
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y libzmq3-dev
        - mkdir build
        - cd build
      script:
        - cmake ..
        - make
        - cd sources/server/tests
        - ctest
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - cmake
            - cmake-data
            - libboost1.55-all-dev
          sources: &sources
            - boost-latest
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y libzmq3-dev
        - mkdir build
        - cd build
      script:
        - cmake ..
        - make
        - cd sources/server/tests
        - ctest
    - os: linux
      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
            - valgrind
            - cmake
            - cmake-data
            - libboost1.55-all-dev
          sources: &sources
            - boost-latest
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
      before_script:
        - sudo apt-get -qq update
        - sudo apt-get install -y libzmq3-dev
        - mkdir build
        - cd build
      script:
        - cmake ..
        - make
        - valgrind --error-exitcode=42 --leak-check=full ./sources/server/tests/fooTests